services:
  agent:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: agent
    ports:
      - "12345:12345"
    depends_on:
      - rabbitmq
      - web
    environment:
      - RABBITMQ_HOST=rabbitmq
